import {
    siAngular,
    siBun,
    siDocker,
    siGit,
    siGithub,
    siGitlab,
    siGo,
    siGooglecloud,
    siJavascript,
    siKubernetes,
    siLaravel,
    siMongodb,
    siMysql,
    siNetlify,
    siNextdotjs,
    siNodedotjs,
    siNpm,
    siNuxt,
    siPhp,
    siPostgresql,
    siPython,
    siReact,
    siRedis,
    siRuby,
    siRust,
    siSqlite,
    siStripe,
    siSvelte,
    siSymfony,
    siTailwindcss,
    siTypescript,
    siVercel,
    siVite,
    siVuedotjs,
    type SimpleIcon,
} from 'simple-icons';

export type { SimpleIcon };

const SIMPLE_ICONS_MAP: Record<string, SimpleIcon> = {
    angular: siAngular,
    bun: siBun,
    docker: siDocker,
    git: siGit,
    github: siGithub,
    gitlab: siGitlab,
    go: siGo,
    golang: siGo,
    googlecloud: siGooglecloud,
    javascript: siJavascript,
    js: siJavascript,
    kubernetes: siKubernetes,
    k8s: siKubernetes,
    laravel: siLaravel,
    mongodb: siMongodb,
    mysql: siMysql,
    netlify: siNetlify,
    nextjs: siNextdotjs,
    'next.js': siNextdotjs,
    nodejs: siNodedotjs,
    'node.js': siNodedotjs,
    npm: siNpm,
    nuxt: siNuxt,
    nuxtjs: siNuxt,
    php: siPhp,
    postgresql: siPostgresql,
    postgres: siPostgresql,
    python: siPython,
    react: siReact,
    redis: siRedis,
    ruby: siRuby,
    rust: siRust,
    s: siSvelte,
    sqlite: siSqlite,
    stripe: siStripe,
    svelte: siSvelte,
    symfony: siSymfony,
    tailwind: siTailwindcss,
    tailwindcss: siTailwindcss,
    ts: siTypescript,
    typescript: siTypescript,
    vercel: siVercel,
    vite: siVite,
    vue: siVuedotjs,
    vuejs: siVuedotjs,
};

export function getSimpleIcon(
    iconName: string | undefined,
): SimpleIcon | undefined {
    if (!iconName) {
        return undefined;
    }

    return SIMPLE_ICONS_MAP[iconName.toLowerCase().trim()];
}
